services:
  flights-redis:
    image: redis:8.4.0-alpine3.22
    container_name: flights-redis
    expose:
      - "6379"
    deploy:
      resources:
        limits:
          memory: 25m
        reservations:
          memory: 25m
    restart: always
    labels:
      log_category: "infra"

  flights-api:
    image: oskarwestmeijer/flights-api:latest
    depends_on:
      - flights-redis
    container_name: flights-api
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 300m
    expose:
      - "8080"
    restart: always
    environment:
      - HAM_API_URL=${HAM_API_URL}
      - HAM_API_KEY=${HAM_API_KEY}
      - REDIS_URL=${REDIS_URL}
    labels:
      log_category: "application"

  flights-ui:
    image: oskarwestmeijer/flights-ui:latest
    depends_on:
      - flights-api
    container_name: flights-ui
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 200m
    expose:
      - "3000"
    restart: always
    environment:
      - NODE_ENV=production
    labels:
      log_category: "application"

networks:
  default:
    name: proxy
    external: true
