services:
  flights-redis:
    image: redis:7.2.4-alpine3.19
    container_name: flights-redis
    expose:
      - "6379"
    deploy:
      resources:
        limits:
          memory: 25m
        reservations:
          memory: 25m
    restart: always
  flights-scheduler:
    image: oskarwestmeijer/flights-scheduler:latest
    depends_on:
      - flights-api
    container_name: flights-scheduler
    deploy:
      resources:
        limits:
          memory: 75m
        reservations:
          memory: 75m
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
  flights-api:
    image: oskarwestmeijer/flights-api:latest
    depends_on:
      - flights-redis
    container_name: flights-api
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 300m
    expose:
      - "8080"
    restart: always
    environment:
      - HAM_API_URL=${HAM_API_URL}
      - HAM_API_KEY=${HAM_API_KEY}
      - REDIS_URL=${REDIS_URL}
  flights-ui:
    image: oskarwestmeijer/flights-ui:latest
    depends_on:
      - flights-api
    container_name: flights-ui
    deploy:
      resources:
        limits:
          memory: 100m
        reservations:
          memory: 100m
    expose:
      - "3000"
    restart: always
    environment:
      - NODE_ENV=production
networks:
  default:
    name: proxy
    external: true
