version: '3.8'

services:
  maps-redis:
    image: redis:7.2.4-alpine3.19
    expose:
      - "6379"
    deploy:
      resources:
        limits:
          memory: 50m
        reservations:
          memory: 50m
  maps-api:
    image: oskarwestmeijer/maps-api:latest
    container_name: maps-api
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 200m
    expose:
      - "8080"
    restart: always
    environment:
      - HAM_API_URL=${HAM_API_URL}
      - HAM_API_KEY=${HAM_API_KEY}
      - REDIS_URL=${REDIS_URL}
  maps-ui:
    image: oskarwestmeijer/maps-ui:latest
    container_name: maps-ui
    deploy:
      resources:
        limits:
          memory: 100m
        reservations:
          memory: 100m
    expose:
      - "3000"
    restart: always
    environment:
      - NODE_ENV=production
networks:
  default:
    name: proxy
    external: true
