services:
  maps-redis:
    image: redis:7.2.4-alpine3.19
    container_name: maps-redis
    expose:
      - "6379"
    deploy:
      resources:
        limits:
          memory: 25m
        reservations:
          memory: 25m
    restart: always
  maps-scheduler:
    image: oskarwestmeijer/maps-scheduler:latest
    depends_on:
      - maps-api
    container_name: maps-scheduler
    deploy:
      resources:
        limits:
          memory: 75m
        reservations:
          memory: 75m
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
  maps-api:
    image: oskarwestmeijer/maps-api:latest
    depends_on:
      - maps-redis
    container_name: maps-api
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 300m
    expose:
      - "8080"
    restart: always
    environment:
      - HAM_API_URL=${HAM_API_URL}
      - HAM_API_KEY=${HAM_API_KEY}
      - REDIS_URL=${REDIS_URL}
  maps-ui:
    image: oskarwestmeijer/maps-ui:latest
    depends_on:
      - maps-api
    container_name: maps-ui
    deploy:
      resources:
        limits:
          memory: 100m
        reservations:
          memory: 100m
    expose:
      - "3000"
    restart: always
    environment:
      - NODE_ENV=production
networks:
  default:
    name: proxy
    external: true
