ktor:
  deployment:
    port: 8080
  application:
    modules:
      - westmeijer.oskar.ApplicationKt.module
api:
  url: "$HAM_API_URL:http://localhost:9000"
  key: "$HAM_API_KEY:secret1234"
redis:
  url: "$REDIS_URL:localhost:6379"