openapi: "3.0.3"
servers:
  - url: https://api.flights.oskar-westmeijer.com
    description: url of production environment
info:
  description: |
    # Introduction
    Provides Hamburg airport flight connections.
    
    - [ https://flights.oskar-westmeijer.com ](https://flights.oskar-westmeijer.com) (Sveltekit frontend)
    - [ https://api.flights.oskar-westmeijer.com ](https://api.flights.oskar-westmeijer.com) (Redoc OpenApi spec)
  version: 1.0.0
  title: Flights-Api
externalDocs:
  description: https://github.com/OskarWestmeijer/flights
  url: 'https://github.com/OskarWestmeijer/flights'

x-tagGroups:
  - name: Resources
    tags:
      - connections_resource_tag
  - name: Response Model
    tags:
      - connections_response_tag
  - name: Response element
    tags:
      - connection_element_tag
      - airport_tag

tags:
  - name: connections_resource_tag
    x-displayName: Connections
    description: Available connections from HAM airport

  - name: connections_response_tag
    x-displayName: ConnectionsResponse
    description: |
      Container for multiple connection elements
      <SchemaDefinition schemaRef="#/components/schemas/ConnectionsResponse" />

  - name: connection_element_tag
    x-displayName: Connection
    description: |
      Element of ConnectionsResponse
      <SchemaDefinition schemaRef="#/components/schemas/Connection" />

  - name: airport_tag
    x-displayName: Airport
    description: |
      Airport
      <SchemaDefinition schemaRef="#/components/schemas/Airport" />



paths:
  /connections:
    get:
      summary: Get all HAM airport connections
      operationId: getConnections
      tags:
        - connections_resource_tag
      responses:
        '200':
          description: Request HAM airport connections
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionsResponse"

components:
  schemas:

    ConnectionsResponse:
      type: object
      description: Container for multiple connection elements
      required:
        - connections
      properties:
        connections:
          type: array
          items:
            $ref: "#/components/schemas/Connection"

    Connection:
      type: object
      description: Connection with HAM airport
      required:
        - hamAirport
        - connectionAirport
        - departureFlightCount
        - arrivalFlightCount
        - totalFlightCount
        - importedAt
      properties:
        hamAirport:
          $ref: "#/components/schemas/Airport"
        connectionAirport:
          $ref: "#/components/schemas/Airport"
        departureFlightCount":
          type: integer
          description: Count of todays departures from HAM
          example: 2
        arrivalFlightCount:
          type: integer
          description: Count of todays arrivals to HAM
          example: 1
        totalFlightCount:
          type: integer
          description: Sum of todays departure and arrival flights between hamburg and the connection airport
          example: 3
        importedAt:
          type: date
          description: UTC date
          example: 2024-09-21T10:11:44Z

    Airport:
      type: object
      description: Details about an airport
      required:
        - airportCode
        - airportName
        - countryCode
        - latitude
        - longitude
      properties:
        airportCode:
          type: string
          description: 3 letter IATA airport code code
          example: HAM
        airportName:
          type: string
          description: Airport name
          example: Hamburg Airport
        countryCode:
          type: string
          description: ISO 3166 ALPHA-2 country code
          example: DE
        latitude:
          type: string
          description: Latitude of the airport
          example: 60.3172
        longitude:
          type: string
          description: Longitude of the airport
          example: 24.9633
