openapi: "3.0.3"
servers:
  - url: https://api.maps.oskar-westmeijer.com
    description: url of production environment
info:
  description: |
    # Introduction
    Provides Hamburg airport flight connections.
    
    - [ https://maps.oskar-westmeijer.com ](https://maps.oskar-westmeijer.com) (Sveltekit frontend)
    - [ https://api.maps.oskar-westmeijer.com ](https://api.maps.oskar-westmeijer.com) (Redoc OpenApi spec)
  version: 1.0.0
  title: Maps-Api
externalDocs:
  description: https://github.com/OskarWestmeijer/maps
  url: 'https://github.com/OskarWestmeijer/maps'
tags:
  - name: flight_routes_resource
    x-displayName: flight-routes
    description: Available flight-routes

  - name: flight_route
    x-displayName: FlightRoute
    description: |
      Element of FlightRouteResponse
      <SchemaDefinition schemaRef="#/components/schemas/FlightRoute" />

  - name: airport
    x-displayName: Airport
    description: |
      Airport
      <SchemaDefinition schemaRef="#/components/schemas/Airport" />

  - name: flight_route_response
    x-displayName: FlightRouteResponse
    description: |
      Container for multiple FlightRoute elements
      <SchemaDefinition schemaRef="#/components/schemas/FlightRouteResponse" />

x-tagGroups:
  - name: Resources
    tags:
      - flight_routes_resource
  - name: Response Model
    tags:
      - flight_route_response
  - name: Response element
    tags:
      - flight_route
      - airport
paths:
  /flight-routes:
    get:
      summary: Get all flight routes
      operationId: getFlightRoutes
      tags:
        - flight_routes_resource
      responses:
        '200':
          description: Request flight routes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlightRouteResponse"

components:
  schemas:

    FlightRouteResponse:
      type: object
      description: Container for multiple flightRoute elements.
      required:
        - flightRoutes
      properties:
        flightRoutes:
          type: array
          items:
            $ref: "#/components/schemas/FlightRoute"

    FlightRoute:
      type: object
      description: Container for multiple flightRoute elements.
      required:
        - flightCount
      properties:
        hamAirport:
          $ref: "#/components/schemas/Airport"
        connectionAirport:
          $ref: "#/components/schemas/Airport"
        flightCount:
          type: integer
          description: Number of flights between hamburg and the connection airport
          example: 4

    Airport:
      type: object
      description: Details about an airport.
      required:
        - airportCode
        - latitude
        - longitude
      properties:
        airportCode:
          type: string
          description: Airport code.
          example: HEL
        latitude:
          type: string
          description: Latitude of the airport.
          example: 60.3172
        longitude:
          type: string
          description: Longitude of the airport.
          example: 24.9633
