name: backend-build-and-test
description: 'backend-build-and-test'
inputs:
  code-cov:
    description: code-cov
    required: true
  java:
    description: Java version
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
        cache: gradle

    - name: Test backend
      shell: bash
      run: |
        docker compose up -d
        ./gradlew clean check

    - name: Build jar
      shell: bash
      run: |
        ./gradlew clean buildFatJar

    - name: Upload Api Jar
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: build/libs/app.jar
        retention-days: 1

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: build/reports/kover/report.xml
      env:
        CODECOV_TOKEN: ${{ inputs.code-cov }}