name: backend-build-and-test
description: 'backend-build-and-test'
inputs:
  code-cov:
    description: code-cov
    required: true
  java:
    description: Java version
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
        cache: gradle

    - name: Test backend
      shell: bash
      run: |
        chmod +x gradlew
        docker compose up -d
        ./gradlew :clean :check --no-parallel
        ./gradlew :scheduler:clean :scheduler:check --no-parallel

    - name: Test scheduler
      shell: bash
      run: |
        chmod +x gradlew
        ./gradlew :scheduler:clean :scheduler:check --no-parallel

    - name: Build jars
      shell: bash
      run: |
        chmod +x gradlew
        ./gradlew buildFatJar
        ./gradlew :scheduler:build

    - name: Upload Api Jar
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: build/libs/app.jar
        retention-days: 1

    - name: Upload Scheduler Jar
      uses: actions/upload-artifact@v4
      with:
        name: flights-scheduler
        path: scheduler/build/libs/flights-scheduler.jar
        retention-days: 1

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: build/reports/kover/report.xml
      env:
        CODECOV_TOKEN: ${{ inputs.code-cov }}