name: backend-build-and-test
description: 'backend-build-and-test'
inputs:
  code-cov:
    description: code-cov
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: gradle

    - shell: bash
      run: |
        chmod +x gradlew 
        docker compose up -d
        ./gradlew clean check
        ./gradlew buildFatJar

    - name: Upload Jar
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: build/libs/app.jar
        retention-days: 1

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: build/reports/kover/report.xml
      env:
        CODECOV_TOKEN: ${{ inputs.code-cov }}