@startuml C4_Elements

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title C4Model Container diagram for Maps

Person(user, "User")

System_Boundary(weatherSystem, "Maps") {
    Container(nginx_proxy, "Proxy", "Nginx")
    Container(maps_api, "API", "Kotlin & Ktor")
    Container(maps_scheduler, "Import-Scheduler", "Kotlin")
    Container(maps_cache, "Cache", "Redis", $descr="Api-data & import-event")
    Container(maps_ui, "UI", "Node & Sveltekit (SSR)")
}
System_Ext(ham_api, "HAM airport Api", "API for current airport connections")


Rel(user, nginx_proxy, "View airport connections", "https")
Rel_R(nginx_proxy, maps_ui, "Route to UI", "https")
Rel_D(nginx_proxy, maps_api, "Route to API", "https")
Rel(maps_ui, maps_api, "Request data for SSR", "https")
Rel(maps_api, maps_cache, "Poll Refresh-Event & Cache Maps-Api response")
Rel(maps_scheduler, maps_cache, "Schedule Refresh-Event every 10min")
Rel_R(maps_api, ham_api, "Refresh airport connections", "https")

LAYOUT_TOP_DOWN()
@enduml